Fix add_machines failure in headless (#830)
* Fix corner case when handling exceptions

Not all exceptions have args, but they should all stringify reasonably.

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1180, in call_exception_handler
    self._exception_handler(self, context)
  File "/home/johnsca/juju/conjure-up/conjureup/events.py", line 90, in handle_exception
    track_exception(exc.args[0])
IndexError: tuple index out of range
```

* Add ipdb to test requirements for debugging

* Fix add_machines failure in headless

Resolve a discrepancy in how add_machines was called between GUI and
headless.  Fixes #829